// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7xcWlCrp5ultpEoRhr-N5u8LKcoEH8qc',
    appId: '1:664198249169:web:6d78e63c05b945a27c23f0',
    messagingSenderId: '664198249169',
    projectId: 'flavorfusion-9ea2d',
    authDomain: 'flavorfusion-9ea2d.firebaseapp.com',
    storageBucket: 'flavorfusion-9ea2d.appspot.com',
    measurementId: 'G-30Q8B08BQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeLwP2mgTc5L1_ABtAYQhIjb1ev9ovL3Y',
    appId: '1:664198249169:android:502885305a9fb4ed7c23f0',
    messagingSenderId: '664198249169',
    projectId: 'flavorfusion-9ea2d',
    storageBucket: 'flavorfusion-9ea2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-T3i2BB5H83pxq603ldJjQjvQ8lSsV6A',
    appId: '1:664198249169:ios:843f5cf13450c7587c23f0',
    messagingSenderId: '664198249169',
    projectId: 'flavorfusion-9ea2d',
    storageBucket: 'flavorfusion-9ea2d.appspot.com',
    iosBundleId: 'com.example.flavorFusion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-T3i2BB5H83pxq603ldJjQjvQ8lSsV6A',
    appId: '1:664198249169:ios:843f5cf13450c7587c23f0',
    messagingSenderId: '664198249169',
    projectId: 'flavorfusion-9ea2d',
    storageBucket: 'flavorfusion-9ea2d.appspot.com',
    iosBundleId: 'com.example.flavorFusion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7xcWlCrp5ultpEoRhr-N5u8LKcoEH8qc',
    appId: '1:664198249169:web:22787750c3ed24577c23f0',
    messagingSenderId: '664198249169',
    projectId: 'flavorfusion-9ea2d',
    authDomain: 'flavorfusion-9ea2d.firebaseapp.com',
    storageBucket: 'flavorfusion-9ea2d.appspot.com',
    measurementId: 'G-TG05ZVG6TM',
  );
}
